import { listCandidateHistory } from "@/lib/data/candidates";
import { CandidateHistoryTable } from "@/components/candidate-history-table";

export const dynamic = "force-dynamic";

export default async function CandidatesPage() {
  const items = await listCandidateHistory();

  return (
    <div className="relative min-h-screen w-full bg-background pb-20">
      {/* Background decoration */}
      <div className="absolute inset-0 z-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/5 via-background to-background pointer-events-none" />

      <div className="relative z-10 mx-auto w-full max-w-5xl px-6 pt-16 lg:pt-24 animate-in fade-in slide-in-from-bottom-8 duration-700">
        <div className="mb-10 space-y-4 text-center md:text-left">
          <div className="inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-sm font-medium text-primary">
            Evaluations
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Candidate history</h1>
          <p className="text-base text-muted-foreground max-w-2xl">
            Review past evaluations and interview questions generated by the AI agent. Click on a candidate to view their full details and chat with the assistant.
          </p>
        </div>
        
        <div className="rounded-xl border border-border/50 bg-card/40 shadow-xl backdrop-blur-xl ring-1 ring-black/5 dark:ring-white/10 p-2">
          <CandidateHistoryTable items={items} />
        </div>
      </div>
    </div>
  );
}
